### PR TITLE
Fix-up install

### PR DESCRIPTION
**Pull request by jakirkham**
- Drop unneeded `setup.py` arguments.
- Package the license file.
- Bump build number to `1`.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please take a look at this, @jcrist ?

**Comment by jcrist** [comment]
Looks good to me. Is `--record=record.txt` no longer standard here? Many recipes I've seen have it.

**Comment by jakirkham** [comment]
So that is only needed in conjunction with `--single-version-externally-managed` when a package uses `setuptools`. However, if the package doesn't use `setuptools` and thus doesn't accept `--single-version-externally-managed`, we have no need for `--record=record.txt` as it is only there to satisfy the requirements of `--single-version-externally-managed`.

**Comment by jakirkham** [comment]
Any more thoughts on this, @jcrist ?

**Comment by jcrist** [comment]
Sorry, thought it was merged already. LGTM. Merging.

**Pull request merged**
